// Have indicators of literal meaning and intended meaning and indicators to differentiate similarities
const answers = {
    zoology: [
        {ch: '动物学',  en: 'zoology', },

        {ch: '脊椎动物',  en: 'vertebrate', },
        {ch: '无脊椎动物',  en: 'invertebrate', },
        
        {ch: '鸟纲',  en: 'aves', },
        {ch: '硬骨鱼纲',  en: 'osteichthyes', },
        {ch: '两栖动物',  en: 'amphibia', },
        {ch: '爬行动物',  en: 'reptilia', },
        {ch: '哺乳动物',  en: 'mammalia', },

        {ch: '扁盘动物门',  en: 'placozoa', },
        {ch: '多孔动物门',  en: 'porifera', },
        {ch: '刺胞动物门',  en: 'cnidaria', },
        {ch: '栉水母动物门',  en: 'ctenophora', },
        {ch: '扁形动物门',  en: 'platyhelminthes', },
        {ch: '中生动物门',  en: 'mesozoa', },
        {ch: '纽形动物门',  en: 'nemertea', },
        {ch: '颚胃动物门 ',  en: 'gnathostomulida', },
        {ch: '腹毛动物门',  en: 'gastrotricha', },
        {ch: '轮虫动物门',  en: 'rotifera', },
        {ch: '线虫动物门',  en: 'nematoda', },
        {ch: '毛颚动物门',  en: 'chaetognatha', },
        {ch: '线形虫动物门',  en: 'nematomorpha', },
        {ch: '动吻动物门',  en: 'kinorhyncha', },
        {ch: '铠甲动物门',  en: 'loricifera', },
        {ch: '棘头动物门',  en: 'acanthocephala', },
        {ch: '环口动物门',  en: 'cycliophora', },
        {ch: '内肛动物门',  en: 'entoprocta', },
        {ch: '苔藓动物门',  en: 'bryozoa', },
        {ch: '帚虫动物门',  en: 'phoronida', },
        {ch: '腕足动物门',  en: 'brachiopoda', },
        {ch: '软体动物门',  en: 'mollusca', },
        {ch: '鳃曳动物门',  en: 'priapulida', },
        {ch: '星虫动物门',  en: 'sipuncula', },
        {ch: '环节动物门',  en: 'annelida', },
        {ch: '缓步动物门',  en: 'tardigrada', },
        {ch: '有爪动物门',  en: 'onychophora', },
        {ch: '节肢动物门',  en: 'arthropoda', },
        {ch: '棘皮动物门',  en: 'echinodermata', },
        {ch: '半索动物门',  en: 'hemichordata', },
        {ch: '脊索动物门',  en: 'chordata', },
    ],
}

for (let prop in answers) {
    for (let i = 0, length = answers[prop].length; i < length; i++) {
        answers[prop][i].audio = `
            <button type="button" onclick="document.querySelector(\`[src='./english/${
                (() => answers[prop][i].en.replace(/ /g, '_').replace(/\//g, '|').replace('\'', '').replace('?', '').toLowerCase())()
            }.mp3']\`).play()">
                &#9654;
                <audio preload="none" src="./english/${(() => answers[prop][i].en.replace(/ /g, '_').replace(/\//g, '|').replace('\'', '').replace('?', '').toLowerCase())()}.mp3"></audio>
            </button>
        `
    }
}

// INDICATE MALE AND FEMALE AND FORMAL AND POLITE




// {ch: '牛',  en: 'cow/ox/bull', },
// {ch: '狗',  en: 'dog', },
// {ch: '猫',  en: 'cat', },
// {ch: '马',  en: 'horse', },
// {ch: '马驹',  en: 'pony', },
// {ch: '老鼠',  en: 'mouse', },
// {ch: '猴子',  en: 'monkey', },
// {ch: '猪',  en: 'pig', },
// {ch: '鹿',  en: 'deer', },
// {ch: '大象',  en: 'elephant', },
// {ch: '长颈鹿',  en: 'giraffe', },
// {ch: '山羊',  en: 'goat', },
// {ch: '猩猩',  en: 'ape', },
// {ch: '动物',  en: 'animal', },
// {ch: '动物园',  en: 'zoo', },
// {ch: '鱷魚',  en: 'aligator/crocodile', },
// {ch: '蝙蝠',  en: 'bat', },
// {ch: '熊',  en: 'bear', },
// {ch: '驢子',  en: 'donkey', },
// {ch: '狐狸',  en: 'fox', },
// {ch: '青蛙',  en: 'frog', },
// {ch: '河馬',  en: 'hippopotomus/hippo', },
// {ch: '袋鼠',  en: 'kangaroo', },
// {ch: '獅子',  en: 'lion', },
// {ch: '兔子',  en: 'rabbit/bunny', },
// {ch: '大老鼠',  en: 'rat', },
// {ch: '犀牛',  en: 'rhinoceros/rhino', },
// {ch: '羊',  en: 'sheep', },
// {ch: '臭鼬',  en: 'Skunk', },
// {ch: '蛇',  en: 'snake', },
// {ch: '老虎',  en: 'tiger', },
// {ch: '烏龜',  en: 'turtle/tortoise', },
// {ch: '狼',  en: 'wolf', },
// {ch: '斑馬',  en: 'zebra', },
// {ch: '龙',  en: 'dragon', },
// {ch: '公鸡',  en: 'rooster/cock', },
// {ch: '蛤蜊',  en: 'clam', },
// {ch: '海豚',  en: 'dolphin', },
// {ch: '水母',  en: 'jellyfish', },
// {ch: '螃蟹',  en: 'crab', },
// {ch: '龙虾',  en: 'lobster', },
// {ch: '八爪鱼',  en: 'octpus', },
// {ch: '牡蛎',  en: 'oyster', },
// {ch: '大虾',  en: 'prawn', },
// {ch: '河豚',  en: 'pufferfish', },
// {ch: '海狮',  en: 'sea lion', },
// {ch: '海马',  en: 'seahorse', },
// {ch: '海豹',  en: 'seal', },
// {ch: '鲨鱼',  en: 'shark', },
// {ch: '鱿鱼',  en: 'squid', },
// {ch: '鲸',  en: 'whale', },
// {ch: '骆驼',  en: 'camel', },
// {ch: '熊猫',  en: 'panda', },
// {ch: '仓鼠',  en: 'hamster', },
// {ch: '人类',  en: 'human', },
// {ch: '鼹鼠',  en: 'mole', },
// {ch: '驼鹿',  en: 'moose', },
// {ch: '水獭',  en: 'otter', },
// {ch: '北极熊',  en: 'polar bear', },
// {ch: '浣熊',  en: 'raccoon', },
// {ch: '海狸',  en: 'beaver', },
// {ch: '蝴蝶',  en: 'butterfly', },
// {ch: '瓢虫',  en: 'ladybug', },
// {ch: '凤凰',  en: 'phoenix', },

// {ch: '',  en: '', },
// {ch: '节肢动物',  en: 'arthropod', },
// {ch: '软体动物',  en: 'mollusc/mollusk', },
// {ch: '甲壳类',  en: 'crustacean', },
// {ch: '蜘蛛纲',  en: 'arachnid', },
// {ch: '棘皮动物',  en: 'echinoderm', },
// {ch: '海绵科',  en: 'spongillidae', },
// {ch: '头足类',  en: 'cephalopod', },
// {ch: '腹足动物',  en: 'gastropods', },
// {ch: '双壳类',  en: 'bivalves', },
// {ch: '安奈里达',  en: 'annelida', },
// {ch: '腔肠纲',  en: 'Coelenterata', },
// {ch: '',  en: 'brachiopods', },
// {ch: '章鱼',  en: 'octopods', },